/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CycleDaySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'position', 'updatedAt', 'userId', 'workoutId'] as const
  $columns = CycleDaySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare workoutId: number | null
}

export class DayOverrideSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'id', 'updatedAt', 'userId', 'workoutId'] as const
  $columns = DayOverrideSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare workoutId: number | null
}

export class ExerciseDefinitionSchema extends BaseModel {
  static $columns = ['createdAt', 'icon', 'id', 'name', 'sectionId', 'updatedAt', 'userId'] as const
  $columns = ExerciseDefinitionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare sectionId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class ExerciseSchema extends BaseModel {
  static $columns = ['createdAt', 'definitionId', 'id', 'name', 'notes', 'position', 'reps', 'restTime', 'sets', 'updatedAt', 'weight', 'workoutId'] as const
  $columns = ExerciseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare definitionId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare position: number | null
  @column()
  declare reps: number | null
  @column()
  declare restTime: number | null
  @column()
  declare sets: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weight: string | null
  @column()
  declare workoutId: number | null
}

export class PerformanceSchema extends BaseModel {
  static $columns = ['createdAt', 'exerciseId', 'id', 'notes', 'reps', 'restTime', 'sessionId', 'updatedAt', 'weight'] as const
  $columns = PerformanceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare exerciseId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare reps: number | null
  @column()
  declare restTime: number | null
  @column()
  declare sessionId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weight: string | null
}

export class ScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'dayOfWeek', 'id', 'updatedAt', 'userId', 'workoutId'] as const
  $columns = ScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dayOfWeek: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare workoutId: number | null
}

export class SectionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'position', 'updatedAt', 'userId'] as const
  $columns = SectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'cycleEndRest', 'cycleRepeat', 'cycleStartDate', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cycleEndRest: boolean
  @column()
  declare cycleRepeat: number | null
  @column.date()
  declare cycleStartDate: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkoutSessionSchema extends BaseModel {
  static $columns = ['completedAt', 'createdAt', 'id', 'scheduledDate', 'startedAt', 'status', 'updatedAt', 'userId', 'workoutId'] as const
  $columns = WorkoutSessionSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare scheduledDate: DateTime | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare workoutId: number | null
}

export class WorkoutSchema extends BaseModel {
  static $columns = ['createdAt', 'icon', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = WorkoutSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}
